[2024-07-25T01:20:11.019+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T01:20:11.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: binance_solusdt_etl_dag.transform_btcusdt_data scheduled__2024-07-25T01:10:00+00:00 [queued]>
[2024-07-25T01:20:11.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: binance_solusdt_etl_dag.transform_btcusdt_data scheduled__2024-07-25T01:10:00+00:00 [queued]>
[2024-07-25T01:20:11.110+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-25T01:20:11.146+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_btcusdt_data> on 2024-07-25 01:10:00+00:00
[2024-07-25T01:20:11.164+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T01:20:11.169+0000] {standard_task_runner.py:64} INFO - Started process 408 to run task
[2024-07-25T01:20:11.176+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'binance_solusdt_etl_dag', 'transform_btcusdt_data', 'scheduled__2024-07-25T01:10:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/binance_solusdt_dag.py', '--cfg-path', '/tmp/tmpge2egfm1']
[2024-07-25T01:20:11.185+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask transform_btcusdt_data
[2024-07-25T01:20:11.345+0000] {task_command.py:426} INFO - Running <TaskInstance: binance_solusdt_etl_dag.transform_btcusdt_data scheduled__2024-07-25T01:10:00+00:00 [running]> on host 5780ad2338c5
[2024-07-25T01:20:11.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='binance_solusdt_etl_dag' AIRFLOW_CTX_TASK_ID='transform_btcusdt_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T01:10:00+00:00'
[2024-07-25T01:20:11.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T01:20:11.622+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T01:20:11.623+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/binance_solusdt_dag.py", line 26, in transform
    data['price'] = str(round(float(data['price'],2)))
                              ^^^^^^^^^^^^^^^^^^^^^^
TypeError: float expected at most 1 argument, got 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/binance_solusdt_dag.py", line 29, in transform
    raise RuntimeError(f"Error transforming data: {e}")
RuntimeError: Error transforming data: float expected at most 1 argument, got 2
[2024-07-25T01:20:11.644+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=binance_solusdt_etl_dag, task_id=transform_btcusdt_data, run_id=scheduled__2024-07-25T01:10:00+00:00, execution_date=20240725T011000, start_date=20240725T012011, end_date=20240725T012011
[2024-07-25T01:20:11.672+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 105 for task transform_btcusdt_data (Error transforming data: float expected at most 1 argument, got 2; 408)
[2024-07-25T01:20:11.717+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T01:20:11.771+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T01:20:11.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
